pagopa/io-backend

- app/.env.example
- app/public/error.html
- app/public/messages.html
- app/src/controllers/authenticationController.js
- app/src/server.js
- app/src/types/user.js
- spid-batch-import/spid-sp.json
@fpersico with this implementation the proxy will redirect the browser to /error.html (configurable) in case of authentication failure. Let discuss if this is OK for the app.
> [#154587208] Redirect to error.html in case of IDP authentication failure.

- package.json
- src/controllers/authenticationController.ts
- src/strategies/spidStrategy.ts
- src/types/user.ts
Remove the international prefix (TINIT-) from the fiscal code value received from SPID
> [#156090306] remove international prefix

- src/services/messagesService.ts
- src/services/profileService.ts
Remove the return of new Promise and mark the function as async
> [#156121044] Align async stile

- package.json
- src/app.ts
- src/controllers/authenticationController.ts
- src/services/messagesService.ts
- src/services/profileService.ts
Add logging when errors occurs
> [#156121070] Add logging when errors occur

- docker-compose.yml
- src/services/__tests__/redisSessionStorage.test.ts
- src/services/redisSessionStorage.ts
I notice that I was using an old version on Redis on my local machine. I've fix the version of the Redis Docker image.
> [#156343142] Fix Redis version in docker-compose

- README.md
- docker/images/tools/Dockerfile
- package.json
- patches/passport-saml+0.31.0.patch
- scripts/generate-api-client.sh
- src/__tests__/passport-saml.test.ts
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/__tests__/messagesController.test.ts
- src/controllers/__tests__/profileController.test.ts
- src/controllers/__tests__/serviceController.test.ts
- src/controllers/authenticationController.ts
- src/services/ISessionStorage.ts
- src/services/__tests__/messagesService.test.ts
- src/services/__tests__/profileService.test.ts
- src/services/__tests__/redisSessionStorage.test.ts
- src/services/redisSessionStorage.ts
- src/types/__tests__/profile.test.ts
- src/types/__tests__/user.test.ts
- src/types/spidLevel.ts
- src/types/user.ts
- yarn.lock
> [#156463232] Return spid level in session

- api.yaml
- public/device.html
- public/notification.html
- src/__tests__/app.test.ts
- src/controllers/__tests__/notificationController.test.ts
- src/controllers/notificationController.ts
- src/services/__tests__/notificationService.test.ts
- src/services/notificationService.ts
- src/types/__tests__/notification.test.ts
- src/types/notification.ts
Some fix to the push notification code after the test session
> [#157387922] Fix typing

- Dockerfile
This is need to autogenerate the models
> [#157123071] Copy api.yml file to Docker image in Dockerfile

- api_proxy.yaml
- src/app.ts
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/__tests__/messagesController.test.ts
- src/controllers/__tests__/notificationController.test.ts
- src/controllers/__tests__/profileController.test.ts
- src/controllers/__tests__/serviceController.test.ts
- src/controllers/authenticationController.ts
- src/services/ISessionStorage.ts
- src/services/__tests__/messagesService.test.ts
- src/services/__tests__/profileService.test.ts
- src/services/__tests__/redisSessionStorage.test.ts
- src/services/redisSessionStorage.ts
- src/types/__tests__/profile.test.ts
- src/types/__tests__/user.test.ts
- src/types/spidLevel.ts
- src/types/user.ts
Also move `/session` to `/api/v1/session` and use the generated `PublicSession`
> [#157969241] Add session endpoint to swagger specs.

- src/app.ts
* [#158521335] Replace custom implementation of `toExpressHandler` to `italia-ts-commons` one in file "app.ts"
> [#158521335] Replace custom implementation of toExpressHandler

- api_public.yaml
- package.json
- src/app.ts
The info endpoint returns the server version
and uptime.
> [#158816228] Provides a public /info endpoint

- package.json
- tsconfig.json
- yarn.lock
See https://github.com/angelozerr/tslint-language-service
Replaces vscode-tslint
> Enables tslint-language-service plugin

- src/services/__tests__/notificationService.test.ts
- src/services/notificationService.ts
* [#157589713] - Insert "deep_link" variable in the payload sent to the push notification server
> [#157589713] define and implement text and format of a push notification message

- src/services/__tests__/notificationService.test.ts
- src/services/notificationService.ts
See https://github.com/teamdigitale/italia-backend/pull/229#issuecomment-406565299
See https://github.com/teamdigitale/italia-app/pull/307#issuecomment-406844942
> [#157589713] The app does not need the deep_link attribute in the notification

- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/__tests__/messagesController.test.ts
- src/controllers/__tests__/notificationController.test.ts
- src/controllers/__tests__/profileController.test.ts
- src/controllers/__tests__/serviceController.test.ts
- src/types/user.ts
actually the backend always returns the same error when decode fails.
> display user decoding errors

- api_notifications.yaml
- api_pagopa.yaml
- api_proxy.yaml
- package.json
- src/app.ts
- src/controllers/__tests__/serviceController.test.ts
- src/controllers/servicesController.ts
- src/server.ts
- src/services/__tests__/messagesService.test.ts
- src/services/messagesService.ts
- src/types/__tests__/service.test.ts
- src/types/api_client/servicePublic.ts
- src/types/service.ts
- yarn.lock
* [#158589222] - Add raw codebase in app, controller and service
* [#158589222] - Upgraded digital-citizenship library dependencies v0.44.0 > v0.47.0
* [#158589222] - Updated proxy api
* [#158589222] - build service
* [#158589222] - lint fix
* [#158589222] - Add tests
* [#158589222] - log errors in case of generic error responses
* [#158589222] - Adapt to snake case variable name "page_size"
> [#158589222] Request services list to opt out

- api_proxy.yaml
- package.json
- src/controllers/__tests__/notificationController.test.ts
InstallationID cannot handle non alphanumeric characters
> [#160659288] fix installationID format

- api_proxy.yaml
- src/services/__tests__/messagesService.test.ts
- src/services/messagesService.ts
@lmorelli986 fai un check pls che potrebbero essercene altri di questi problemi
> [#160670643] Fixes parsing of API response for GetMessage

- package.json
- src/clients/api.ts
- src/clients/pagopa.ts
- src/services/IApiClientFactory.ts
- src/services/IPagoPAClientFactory.ts
- src/services/__tests__/pagoPAProxyService.test.ts
- src/services/apiClientFactory.ts
- src/services/messagesService.ts
- src/services/pagoPAClientFactory.ts
- src/services/pagoPAProxyService.ts
- src/services/profileService.ts
I've added some comments inline to explain the changes.
The current master contains an error in activatePayment that prevents the API call to work at all.
> [#160704826] fix rest api calls

- api_proxy.yaml
@cloudify v0.59.0 tag of the API must be created.
> Update API definitions to v0.59.0

- api_backend.yaml
- package.json
- src/types/__tests__/profile.test.ts
- src/types/profile.ts
[#163190244] ToS parameter to user profile.
> [#163190244] Add ToS parameter to profile

- src/utils/__tests__/idpLoader.test.ts
- src/utils/idpLoader.ts
> [#164984224] Use HTTP:Redirect Location for IDP

- api_backend.yaml
- api_notifications.yaml
- api_pagopa.yaml
- package.json
- src/controllers/__tests__/profileController.test.ts
- src/services/__tests__/profileService.test.ts
- src/types/__tests__/profile.test.ts
Use new functions.
Profile Service handle `is_email_enabled` property.
> [#166672369] Update api specs with new functions

- .circleci/config.yml
- Dockerfile
- docker-compose.yml
- docker/images/tools/Dockerfile
Fix an error on `docker build` command [#168542131](https://www.pivotaltracker.com/story/show/168542131)
Fix `docker-compose.yml` for local build on non-linux systems [#168427815](https://www.pivotaltracker.com/story/show/168427815)
> [#168542131] Fix Dockerfile build error

- api_backend.yaml
- src/app.ts
- src/controllers/__tests__/profileController.test.ts
- src/controllers/profileController.ts
- src/services/__tests__/profileService.test.ts
- src/services/profileService.ts
A new API is provided to retrieve only the user profile from the functions.
> [#168779334] New API to get user profile from the functions

- src/services/__tests__/redisSessionStorage.test.ts
- src/services/redisSessionStorage.ts
- src/services/redisStorageUtils.ts
- src/utils/errorsFormatter.ts
The `/logout` endpoint when called return always status `500` Internal Server Error.
> [#168726455] fix 500 error when logout is called

- api_pagopa.yaml
- src/__mocks__/request.ts
- src/app.ts
- src/controllers/__tests__/pagoPAController.test.ts
- src/controllers/pagoPAController.ts
This PR is dependent from #556 
Merge after #556 and rebase from master
> [#170259398] Add new API getUser for PagoPA with Extended infos

- .auto-changelog.json
- .gitignore
- .release-it.js
- package.json
- preview.hbs
- yarn.lock
Add [release-it](https://github.com/release-it/release-it) command
> [#155184481] chore: adds release-it

- package.json
- src/config.ts
- yarn.lock
Added Strict Response Validation configuration and RACComparison setting to `minimum`
> [#171467326] Upgrade io-spid-commons to v.2.5.0

- api_backend.yaml
- src/app.ts
- src/clients/api.ts
- src/controllers/__tests__/serviceController.test.ts
- src/controllers/servicesController.ts
- src/services/__tests__/messagesService.test.ts
- src/services/messagesService.ts
remove unused endpoint `/profile/sender-services` (getServicesByRecipient)
> [#171683935] remove unused endpoint

- .env.example
- docker-compose.yml
- docker/images/azurite/Dockerfile
- package.json
Adds files to let devs debug inside docker
> [#171949770] add debug environment

- src/app.ts
- src/controllers/authenticationController.ts
- src/services/tokenService.ts
- src/strategies/bearerSessionTokenStrategy.ts
- src/types/__tests__/user.test.ts
- src/types/user.ts
- src/utils/appinsights.ts
Enables tracking user sessions in application insights - a new unique ID gets attached to each session and gets propagated across requests
> Adds session tracking to application insights

- src/controllers/userDataProcessingController.ts
- src/services/__tests__/userDataProcessingService.test.ts
- src/services/userDataProcessingService.ts
Inserted conflict error on userDataProcessing upsert services and controller
> [#172693963] - UserDataProcessing transient statuses management

- package.json
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/__tests__/sessionController.test.ts
- src/controllers/authenticationController.ts
- src/services/ISessionStorage.ts
- src/services/__tests__/redisSessionStorage.test.ts
- src/services/redisSessionStorage.ts
- yarn.lock
added user login block check. If a user has requested to delete its own data, login is blocked until all data are processed, in this time range login returns 403.
> [#172885142] block blacklisted users

- Dockerfile
we need to copy this file for Docker build
> [#173031257] added missing reference

- api_bonus.yaml
latest soap specs by INPS includes some extra field
> [#173081682] update bonus spec according to latest INPS specs

- src/app.ts
- src/clients/bonus.ts
- src/controllers/__tests__/bonusController.test.ts
- src/controllers/bonusController.ts
- src/services/__tests__/bonusService.test.ts
- src/services/bonusService.ts
Added the implementation of the `getBonusEligibilityCheck` proxy method and exposed the `GET /bonus/eligibility` endpoint
> [#173017441] implement getBonusEligibilityCheck method

- src/__mocks__/request.ts
- src/app.ts
- src/clients/bonus.ts
- src/controllers/__tests__/bonusController.test.ts
- src/controllers/bonusController.ts
- src/services/__tests__/bonusService.test.ts
- src/services/bonusService.ts
~This is a draft until #671 gets merged~
* implemented proxy endpoint for bonus' `startBonusActivationProcedure`
> [#173017550] start activation procedure

- src/__mocks__/request.ts
- src/app.ts
- src/clients/bonus.ts
- src/controllers/__tests__/bonusController.test.ts
- src/controllers/bonusController.ts
- src/services/__tests__/bonusService.test.ts
- src/services/bonusService.ts
* implemented proxy endpoint for bonus' `getAllBonusActivations`
> [#173034992] Add endpoint to get bonuses for user

- api_bonus.yaml
- add 202 status code and payload definition
- edit 201 payload
> [#173248200] Add 202 status code on bonus activation

- api_bonus.yaml
- src/controllers/__tests__/bonusController.test.ts
- src/services/__tests__/bonusService.test.ts
Removed useless ref:
- MaxBonusAmount
- MaxBonusTaxBenefit
> Remove useless refs from bonus API specification

- api_bonus.yaml
Review of openapi spec diffs between io-backend and io-functions-bonus
> [#173421579] Align OpenAPI spec to io-functions-bonus

- src/controllers/bonusController.ts
- src/services/__tests__/bonusService.test.ts
- src/services/bonusService.ts
- src/utils/__tests__/date.test.ts
- src/utils/date.ts
- src/utils/responses.ts
Added check for logged user's age in order to make bonus request unavailable for not adult users.
> [#173530790] Adult Check on startBonusEligibilityCheck

- api_backend.yaml
- update reference to io-function-commons 10.7.0
> [#173783396] Updated api spec with UserDataProcessingStatus ABORTED

- api_bonus.yaml
- src/controllers/bonusController.ts
- src/services/__tests__/bonusService.test.ts
- src/services/bonusService.ts
- src/utils/responses.ts
Modified return type to 451 in order to discriminate error on app, while requesting a bonus activation
> [#173768306] Change adult check HTTP response on DSU eligibility check

- src/services/__tests__/redisSessionStorage.test.ts
- src/services/redisSessionStorage.ts
On user logout current `SESSIONINFO` value is removed from `USERSESSIONS` set
> [#174819389] Update USERSESSIONS set on logout

- api_auth.yaml
- api_backend.yaml
- package.json
- src/app.ts
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/authenticationController.ts
- src/types/user.ts
Created a new swagger file for authentication routes.
Was added missing `/logout` specification
Was fixed the specification of `/user-identity` API because the base path was wrong compared with the real implementation.
> [#175146179] Fix user-identity spec and add logout spec

- package.json
- yarn.lock
Update `io-spid-commons` to use https://github.com/pagopa/io-spid-commons/pull/54
> [#175499507] update spid-commons

- azure-pipelines.yml
- azure-templates/deploy-steps.yml
> deploy with linux appservice

- .env.example
- README.md
- api_bonus.yaml
- src/app.ts
- src/config.ts
- src/controllers/__tests__/bonusController.test.ts
- src/controllers/bonusController.ts
- src/services/__tests__/bonusService.test.ts
- src/services/bonusService.ts
- src/utils/express.ts
- src/utils/responses.ts
As Bonus Vacanze cannot be requested anymore, we can get rid of all the code related su such features:
* `BONUS_REQUEST_LIMIT_DATE` env var in configuration
* Endpoints to always return `404`
* unused code to be removed
There is a known issue on the infrastructure: when applying a change, environment variables which are date string, are converted unexpectedly. UTC ISO date format is exposed to such issue, thus `BONUS_REQUEST_LIMIT_DATE` may be in an unexpected format causing the application boot to fail.
Locally using `io-mock`
> [#176458169] Remove unused code path for bonus activation

- api_cgn.yaml
- Add `StartCgnActivation` API specs
A CGN should be activated by requesting from in APP wallet home section. This PR is intended for exposing API specs to APP side for documentation purpose.
Please refer to related [story](https://www.pivotaltracker.com/story/show/176515654) for further informations.
No tests needed.
> [#176515654] Add Start CGN Activation api specs

- api_cgn.yaml
- package.json
- src/controllers/__tests__/cgnController.test.ts
- src/controllers/cgnController.ts
- src/services/__tests__/cgnService.test.ts
- src/services/cgnService.ts
- Refactor CGN Api specs
- Fix tests
While a citizen requests for a CGN and he's between 18 up to 30 years old, he wants also activate an EYCA card ( CGN and EYCA are co-badged ), so we have to refactor Card Status specs in order to reuse common definitions for EYCA and CGN cards, see this [PR](https://github.com/pagopa/io-functions-cgn/pull/19).
It has been tested by performing unit tests and integration test.
> [#176782168] CGN Api specs refactor

- api_cgn.yaml
- `api_cgn.yaml` updated with some specific definitions
After the API's integration provided in [here](https://github.com/pagopa/io-functions-cgn/pull/23), we must update openapi specs as well, to allow APP generate correct client types.
It has been tested by performing unit tests .
> [#176924278] Add specific openapi defs for EYCA CCDB API integration

- api_cgn.yaml
- package.json
- Update io-functions-cgn refs to release version
In order to avoid io-functions-cgn merge operations on master can break IO APP CI pipelines, we must point to a specific version instead of `master`. See this [story](https://www.pivotaltracker.com/story/show/177145295) for further informations.
No tests needed
> [#177145295] Add release ref on io-functions-cgn

- .devops/deploy-pipelines.yml
Fix `generatorPackageName` into `PublishClientSDKstoNPM` stage
> fix sdk generator in deploy pipeline

- api_backend.yaml
- package.json
- yarn.lock
Update `MessageContent` to functions-commons version 20.4.0, in order to include new `EUCovidCert` content
> Update MessageContent to v20.4.0

- api_eucovidcert.yaml
- src/controllers/__tests__/eucovidcertController.test.ts
- src/services/__tests__/eucovidcertService.test.ts
- src/services/eucovidcertService.ts
Add ProblemJson object to responses with status code 400 and 500. 
**NOTE: Wait PR https://github.com/pagopa/io-functions-eucovidcerts/pull/26 to be merged**
In order ti properly generate client handler in io-backend, add missing return ProblemJson 
io-mock
> [#P-235] Handle ProblemJson from fn-eucovidcert and return it

- src/config.ts
1. increase log sampling from 20 to 5 (lowest value reduce log ingestion in application insights)
Cost savings reducing log data ingestion in application insights
Same change applied on fn3app1 https://github.com/pagopa/io-functions-app/pull/156
> [#IP-122] Reduce log data ingestion

- src/controllers/notificationController.ts
This is a workaround to quickly resolve a scenario in which we fail to handle concurrency properly.
When a login is requested by App IO, [the login controller fires a `DeleteInstallation` event](https://github.com/pagopa/io-backend/blob/925e59f10c0ee59178e917a9af08b7ba7c7ae951/src/controllers/authenticationController.ts#L226) to make sure no other device will receive push notifications for the Citizen. This complies with the business rule for which a Citizen can be logged to one device at most.
After a successful login, App IO communicates its `pushChannel` so that it can be bind to the current logged Citizen by firing a `CreateOrUpdateInstallation` event. 
We have empirical evidence that deletes are executed after inserts, so that new installations are cleared just as they are stored. …
> Add delay when updating an installation id

- api_mit_voucher.yaml
- package.json
- src/controllers/__tests__/mitVoucherController.test.ts
- src/controllers/mitVoucherController.ts
- Add MitVoucherToken type on mit voucher api specs
- Update MitVoucherController with new type's mapping
It solves a problem with NonEmptyString serialization on Success Response
> [#ISV-29] Add Better Mit Voucher token typing

- package.json
- src/types/notification.ts
- yarn.lock
- Upgrade typescript to v4.3.5
- Fix `FiscalCodeHash` to be a `NonEmptyString`: typescript does not anymore allow a type to have two different "kind" at the same time
Upgrade typescript to last version
> [#IP-325] Upgrade typescript to v4.3.5

- api_session.yaml
* update references to `io-functions-commons`
To use a newer version of `io-functions-commons`, so that definitions make no reference to old `italia-ts-commons`
> Update common definitions on `api_session.yaml`

- Dockerfile
- api_backend.yaml
- package.json
- src/services/__tests__/pagoPAProxyService.test.ts
- src/services/pagoPAProxyService.ts
- src/utils/responses.ts
The purpose of this PR is to update the responses received from the `io-pagopa-proxy`
- Updated
- reference api spec of `io-pagopa-proxy` to `v0.14.1`
- `PaymentProblemJson` response of `/payment-requests/{rptId}` and `/payment-activations` with  [detail_v2](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/384141710/RFC+App+IO+-+pagopa-proxy+Gestione+codici+di+errore#Opzione-3) field
- test `pagoPAProxyService.test.ts` 
For the GetPayment and ActivatePayment api, to enrich the error response with a new `detail_v2` field, [errors code returned by NODO](https://github.com/pagopa/pagopa-nodo4-nodo-dei-pagamenti/blob/e7f3cdb54119ac248b40f993d3ca4c8f328b6785/common/src/main/scala/eu/sia/pagopa/common/util/DigitPaErrorCodes.scala#L4).
On terminal, in to root project folder, typing : 
`yarn …
> [PAG-754] upd pagopa-proxy service with new detail_v2 response

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- Upgrade azure devops templates to v17
- New healthcheck management
Fix healthcheck
> [IP-415]  Fix Healthcheck

- src/app.ts
- src/config.ts
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/authenticationController.ts
- src/strategies/localStrategy.ts
- src/types/user.ts
New feature flag to enable minimum age allowed for users.
`AuthenticationController` can disable session and profile creation for user under the limit age.
When a blocked user try to login a custom event is sent to AI.
A minimum age is required to complete the login.
unit test
> [#IC-109] User login age limit

- api_backend.yaml
- package.json
- src/services/messagesService.ts
Update `PublicService` and `ServiceMetadata` with the new Special Service specification.
Update the object specifications for Special Services updated on the new version of `io-functions-commons` and the new client generated from the `io-functions-app` openapi specifications.
not tested yet
> [#IC-45] Update Special Services specification

- api_backend.yaml
- package.json
The purpose of this PR is to : 
- manage `PAA_SYSTEM_ERROR` that could emitted from [EC](https://docs.google.com/spreadsheets/d/16VBHabKr4b3HBII-P0VuLByhWLRSU4Y3-TwYMu077MU/edit#gid=0) and returned by [io-pagopa-proxy](https://github.com/pagopa/io-pagopa-proxy)
- add 504 gateway timeout in api spec for:
- GET payment-requests/${rptId}
- POST payment-activation
- GET payment-activation/${ccp}  
Updated : 
- In order to do this we updated pagopa-proxy version api reference to `v0.20.0`
To allow the [AppIO](https://github.com/pagopa/io-app) to show the [right error message](https://pagopa.atlassian.net/wiki/spaces/IOAPP/pages/441155670/Errori+in+verifica+e+attivazione) to the citizen
> [IABT-1292] manage PAA_SYSTEM_ERROR and 504 gtw error

- src/services/tokenService.ts
> [#IC-158] Inverted name and family name for zendesk token

- src/config.ts
CGN operator search functions need an httpsClient.
> Fixed client to make https call to functions

- api_cgn_operator_search.yaml
Added openapi specs for /discount-bucket-code
> Added missing openapi spec

- package.json
This PR upgrades the min app versione from `1.27.0 `to `1.32.0.3`
> [IAC-125] Upgrade min app version

- README.md
- src/config.ts
Add new Environment `SAML_REQUEST_EXPIRATION_PERIOD_MS` with default value `600.000` (10 minutes)
The SamlConfig for SPID and CIE login has `requestIdExpirationPeriodMs` provided
We need to reduce the default value of `requestIdExpirationPeriodMs` from 15 minutes to 10 minutes. We also add the possibility to change this TTL with app configuration without new commits.
not tested
> [#IC-226] Add Env to configure SAML requests cache TTL

- api_backend.yaml
- api_messages_temp.yaml
- package.json
- src/controllers/messagesController.ts
- src/services/messagesService.ts
this PR depends on https://github.com/pagopa/io-functions-commons/pull/238
this PR depends on https://github.com/pagopa/io-functions-app/pull/243
- Update openapi
> [#IC-294] update GetMessages endpoint

- api_backend.yaml
- package.json
Added new endpoint to upsert message status attributes
This PR depends on pagopa/io-functions-app#244
> [#IC-327] Added endpoint and pointed fn-app with upsert message status defined

- src/__mocks__/user_mock.ts
- src/controllers/__tests__/notificationController.test.ts
- src/controllers/__tests__/zendeskController.test.ts
- src/services/__tests__/redisSessionStorage.test.ts
- src/services/__tests__/redisUserMetadataStorage.test.ts
- src/types/__tests__/user.test.ts
Change tokens mocks used in unit tests.
Fix unit test for `RedisSessionStorage#set`
Some tests in Redis session storage was wrong. They don't fail because the input conditions was invalid.
unit test
> [#IC-378] Fix unit test RedisSessionStorage#set

- api_backend.yaml
- package.json
- src/app.ts
- src/controllers/__tests__/messagesController.test.ts
- src/controllers/messagesController.ts
- src/services/__tests__/messagesService.test.ts
- src/services/messagesService.ts
- Add new UpserMessageStatus endpoint implementation
> [IC-377]  Add upsert message status

- .env.example
- README.md
- package.json
- src/app.ts
- src/clients/app-messages.client.ts
- src/config.ts
- src/controllers/__tests__/messagesController.test.ts
- src/controllers/messagesController.ts
- src/services/messagesServiceSelector.ts
- src/services/newMessagesService.ts
- src/utils/comma-separated-list.ts
This PR depends on https://github.com/pagopa/io-infra/pull/142
- add new client for fn-app-messages
- add messagesServiceSelector for choosing between services (fn-app and fn-app-messages)
Switch to new fn-app-messages function
> [#IC-388]  Add new fn-app-messages client + A/B testing

- src/controllers/__tests__/messagesController.test.ts
- src/services/messagesServiceSelector.ts
- Include beta tester if `canary` FF is enabled
> [#IC-405] [FIX] Include beta tester if `canary` FF is enabled

- .env.example
- README.md
- src/config.ts
- src/types/__tests__/commons.test.ts
- src/types/commons.ts
- src/utils/__tests__/thirdPartyConfig.test.ts
- src/utils/thirdPartyConfig.ts
- Add new `ThirdPartyConfig`, `ThirdPartyConfigList` and `ThirdPartyConfigListFromString`
- add new `THIRD_PARTY_CONFIG_LIST` env variable, with empty array as default
- add `jsonFromString` decoder and `fallback` utility
New third-party message implementation
Unit tests
> [#ICC-73]  Add ThirdPartyConfiguration

- api_backend.yaml
- src/app.ts
- src/controllers/messagesController.ts
- src/utils/responses.ts
This PR depends on [io-fn-commons #ICC-87](https://github.com/pagopa/io-functions-commons/pull/275)
- add new `getThirdPartyMessage` and `getThirdPartyMessageAttachment` openapi definitions
- add new `getThirdPartyMessage` and `getThirdPartyMessageAttachment` in MessageController, returning `501 - Not Implemented`
Expose new endpoint for retrieving Third Party message details and attachments
io-mock
> [#ICC-87] New Third party get message and attachments endpoints definition

- src/app.ts
* disable ip filter middleware for `/notifiy` endpoint
This is a remediation to _stop the bleeding_ after a production failure. We had a breaking changes in the app service such as we are receiving an `ipv6` address instead of `ipv4` as we used to and we expected to. The result is that push notifications fail with due to access error and thus are discarded.
A more consistent solution will be provided, but this is to restore the application functionality for users.
> [ICC-109] Disable ip filter for notification

- .env.example
- README.md
- src/app.ts
- src/config.ts
This PR depends on https://github.com/pagopa/io-infra/pull/183
- add `FF_ENABLE_NOTIFY_ENDPOINT` and `FF_ENABLE_SESSION_LOCK_ENDPOINT` feature flags
- enable /notify and /sessions/:fiscal_code/lock endpoint based on new feature flags
NOTE: both FF are related to new env variable `IS_APPBACKENDLI`
Fix
Io-mock
> [ICC-113] [FIX] Add FF for enabling notify and session lock endpoints

- openapi/api-third-party.yaml
- package.json
- add new `api-third-party.yaml`
Common specification to enable integration with Third Party services for retrieving Third Party messages and attachments
> [#ICC-78]  Add openapi for Third Party services

- src/clients/__tests__/third-party-service-client.test.ts
- src/clients/third-party-service-client.ts
This PR depends in #899 
- Handle authorization based on Third Party configuration
Enable Third Party messages on IO
Unit Tests
> [#ICC-75]  Choose auth method for Third Party Services calls

- src/services/newMessagesService.ts
- log title, detail and type when error occurred retriving a TP message
> [FIX] log title, detail and type when error occurred retriving a TP message

- src/adapters/__tests__/pnFetch.test.ts
- src/adapters/pnFetch.ts
> [#ICC-130] Fix errorResponse issue

- openapi/api-piattaforma-notifiche.yaml
- package.json
- src/__mocks__/pn-response.ts
- src/adapters/__tests__/pnFetch.test.ts
- src/utils/middleware/dueDate.ts
- yarn.lock
The PN client do not properly decode the ISO date when they have the timezone set.
update ts-commons
add test for pn adapter
fix dueDate
> [#ICC-139] Add support to PN client for iso date with timezone

- .devops/deploy-pipelines.yml
Removed `PublishClientSDKstoNPM` stage from the deploy pipeline.
Removing a now unused stage from the deploy pipeline.
> [#IOCIT-73] removed publishsdktonpm stage from deploy pipeline

- src/adapters/pnFetch.ts
- src/clients/__tests__/third-party-service-client.test.ts
Fix adapter regex for matching attachment_url
> [#ICC-146] Fix adapter regex for matching attachment_url

- api_cgn.yaml
- package.json
- src/controllers/__tests__/cgnOperatorSearchController.test.ts
- yarn.lock
Upgrade `@pagopa/openapi-codegen-ts` to `v11.1.2`
Fix build error for missing type definition in OpenApi specs.
Upgrade the codegen to the last version that adds supporto for OAS3.
build and unit test
> [#IOCIT-76] Upgrade Codegen and fix CGN specs

- package.json
- yarn.lock
Updated the following libraries:
* `passport`
* `io-spid-commons`
Vulnerability fix
I tested session info endpoints of io-backend regarding those APIs:
* myportal
* fims
* pagopa proxy
* zendesk
* bpd
no problems tracked so far.
> [#IOCIT-82] passport update

- openapi/api-piattaforma-notifiche.yaml
Piattaforma Notifiche added a new status "CANCELLED". The openapi spec has been updated to accept this new value.
Add CANCELLED to NotificationStatus enum in the openapi spec
Proper retrieve notification with status CANCELLED
unit test
> [#ICC-179] Add missing CANCELLED value to NotificationStatus

- openapi/api-piattaforma-notifiche.yaml
The field pagopaform is no more required in PN specs. We removed it from our freezed specs.
removed pafopaform form specs
fixed typo
Some PN message details (es. a CANCELLED one) could not be decoded properly due to pagopaform missing. In this way, the PN message is will be marked as read, but the user have received an error.
> [#ICC-180] Remove pagopaform from required fields in PN specs

- package.json
- src/clients/third-party-service-client.ts
- yarn.lock
- Upgrade `@pagopa/openapi-codegen-ts`
- Remove custom array buffer download implementation, since it's now handled by generated client
Refactor after latest features added to openapi-codegen
Unit tests
> [ICC-188] Upgrade `@pagopa/openapi-codegen-ts` and remove custom implementation

- README.md
Added `IS_APPBACKENDLI` documentation on `README.md`
As stated [here](https://github.com/pagopa/io-mock/pull/61#discussion_r951102470), this variable needs more documentation because enables two endpoints (`/notify` and `/lock`)
> Update IS_APPBACKENDLI documentation on README

- src/__mocks__/user_mock.ts
- src/app.ts
- src/controllers/__tests__/sessionController.test.ts
- src/controllers/__tests__/zendeskController.test.ts
- src/controllers/sessionController.ts
- src/controllers/zendeskController.ts
- src/strategies/__tests__/bearerZendeskTokenStrategy.test.ts
- src/strategies/bearerZendeskTokenStrategy.ts
- src/utils/profile.ts
`/session` Added a suffix of 8 bytes to zendeskToken from the hash of the profile email address. If email is not valid and/or GetProfile returns an error we generate a random suffix. 
`bearerZendeskTokenStrategy` Strip of additional 8 bytes from the token received from zendesk if present.
We need Zendesk to renew the JWT when an user change its email address.
yarn build
yarn lint
yarn test
> [#IOCIT-90] Modify /session at runtime to change the zendeskToken if profile email address change

- package.json
This PR upgrades `min_app_version` to `2.3.0`
See https://pagopaspa.slack.com/archives/CQVJ1JES2/p1657206462831859 for more info
> [IAI-211] Upgrade `min_app_version` to `2.3.0`

- api_backend.yaml
- Update io-fn-commons dependencies on `api_backend.yaml`
This is required in order to align dependencies realease.
No tests needed
> [#ICC-244] Upgrade io-fn-commons dependencies

- openapi/api-piattaforma-notifiche.md
- openapi/api-piattaforma-notifiche.yaml
- package.json
- src/__mocks__/pn-response.ts
- src/__mocks__/pn.ts
- yarn.lock
This PR will update the Piattaforma Notifiche API definition to the last available version.
This version is a freezed one: this will be used for first production release. 
update codegen version
replace PN definitions with freezed one
fix tests
Keep integration between PN and IO working.
unit test
> [#ICC-227] Update PN definitions with freezed one

- src/adapters/__tests__/pnFetch.test.ts
- src/adapters/pnFetch.ts
- src/clients/__tests__/third-party-service-client.test.ts
- make attachment id unique by combining `id` with `iun`
bugfixing
unit test
> [#ICC-246] make attachment id unique

- api_backend.yaml
- package.json
- src/controllers/__tests__/profileController.test.ts
- src/services/__tests__/profileService.test.ts
- src/types/profile.ts
Depends on https://github.com/pagopa/io-functions-commons/pull/297
Depends on https://github.com/pagopa/io-functions-app/pull/260
* imported new openapi specs
* updated backend openapi specs
* updated mapper to Initialized Profile 
We need a new profile preference to get/set opt-in for descriptive push notifications.
TO TEST
> [#IOCIT-149] New profile preference for Descriptive Push Notifications

- src/services/__tests__/notificationService.test.ts
- src/services/notificationService.ts
- [[#IOCIT-197] remove service name from notification title + add test](https://github.com/pagopa/io-backend/commit/9431be13c4ce00273a235d2a41baebc8d408c0da)
Do not show service name when verbose push notification are enabled
> [#IOCIT-197] Remove service name from notification title

- src/app.ts
- src/config.ts
- src/services/__tests__/notificationServiceFactory.test.ts
- src/services/notificationServiceFactory.ts
> [#IOCIT-177 #ICC-276] Add pushnotif routing for canary users

- .devops/code-review-pipelines.yml
- .github/workflows/pr-title-linter-and-linker.yaml
- Dangerfile.ts
- package.json
- yarn.lock
- Remove danger from code-review
- Remove all danger packages
- Add new github action
> [#ICC-312] Remove danger

- api_backend.yaml
- src/controllers/messagesController.ts
- src/services/__tests__/newMessagesService.test.ts
- src/services/newMessagesService.ts
- src/utils/responses.ts
This PR depends on #965 
- Return 415 instead of 410 in case of wrong file format
Discriminate download error
> [#ICC-310]  Return 415 in `getThirdPartyMessageAttachment` endpoint

- package.json
- src/__tests__/app.test.ts
- src/__tests__/services-api.test.ts
- src/app.ts
- src/utils/redis.ts
- yarn.lock
> [#IOCIT-283] Track custom events for redis events

- package.json
* [[#IOCIT-280] fix invalid glob patterns inside jest configuration](https://github.com/pagopa/io-backend/commit/203a7a3b7017343e61074836cea50d8149855c97)
Motivation: restore coverage analysis. 
Context: invalid glob patterns where present in the jest configuration. curly brackets are used for multiple matches but was used for a single match. this resulted in a pattern with `{ts}` took as a whole string literal, therefore breaking the coverage analysis. since backend 9.8.0 jest was updated to major `24`(related [PR](https://github.com/pagopa/io-backend/pull/959)), which included breaking changes for wrong patterns, more info [here](https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly#breaking-changes).
coverage correctly generated
> [#IOCIT-280] fix invalid glob patterns inside jest configuration

- openapi/consumed/api-piattaforma-notifiche.yaml
- src/__mocks__/pn-response.ts
- src/__mocks__/pn.ts
- src/adapters/__tests__/pnFetch.test.ts
- src/adapters/pnFetch.ts
- src/clients/__tests__/third-party-service-client.test.ts
- Update consumed PN specs
- Update code to fit the new Third Party Message shape
- Add ` Accept: "application/io+json"` header
- Update tests
Call new PN endpoint
Unit tests
> [#ICC-266]  Update PN client

- openapi/consumed/lollipop_consumer_example.yaml
- openapi/generated/lollipop_definitions.yaml
- src/__tests__/lollipop.test.ts
- [[#IOCIT-355] fix lollipop_definitions.yaml](https://github.com/pagopa/io-backend/commit/cd0c0bcbf65bd2adbe0dfc8646fbf81681594d4f)
- [[#IOCIT-355] add lollipop_consumer_example.yaml](https://github.com/pagopa/io-backend/commit/5c944a49b47911efd0c9db48c7ac46f42ffb3e96)
Enable LolliPoP protocol
> [#IOCIT-355]  Add LolliPoP Consumer openapi sample

- src/controllers/authenticationController.ts
Remove logs
debug logs are not needed in production.
not tested
> Remove logs with SAML response

- openapi/consumed/lollipop_first_consumer.yaml
Adjust response indentation to let the client decode the `ProblemJson`
> Fix indentation in `lollipop_first_consumer.yaml`

- package.json
- src/__tests__/lollipop-consumer.test.ts
- src/app.ts
- src/types/lollipop.ts
- src/utils/express.ts
- yarn.lock
The raw body is now a Buffer instead a `Readable`
The azure function skip the body if is sent as `Readable`.
unit test and local execution
> Refactor rawBody as Buffer for azure function compatibility

- openapi/consumed/api-piattaforma-notifiche.md
- openapi/consumed/api-piattaforma-notifiche.yaml
- src/__mocks__/pn-response.ts
- src/__mocks__/pn.ts
- src/adapters/pnFetch.ts
- src/clients/__tests__/third-party-service-client.test.ts
- update pn swagger
- update attchament path from 'sent' to 'received'
The PN attachment are now exposed in a differents path. To keep integration online we update the swagger and all the path reference in the pn adapter.
unit test
> [#ICC-370]  Update PN swagger and attachment path

- api_public.yaml
- package.json
- yarn.lock
Upgrade `io-spid-commons` to `v10.1.1`
Fix remove `,` from public API specs
The new version of `io-spid-commons` add the support for 2 new SPID IdP (EHT and Infocamere)
not tested
> [#IOPID-131] Add support for eht and infocamere SPID IdP

- api_io_sign.yaml
- Error 500 content response according to OA3 Specs
Validation with https://github.com/pagopa/opex-dashboard failed
> [SFEQS-1357]: Fix 500 response content

- api_lollipop_first_consumer.yaml
- package.json
- src/controllers/firstLollipopConsumerController.ts
Added `api_lollipop_first_consumer.yaml`
Expose first LC endpoint
> [#IOPID-94] Add first LC openapi

- api_public.yaml
- remove intesaid from login `EntityId` parameter enum
Intesa Id is no longer a SPID provider.
> [#IOPID-143] remove intesaid from login parameter enum

- api_lollipop.yaml
- api_public.yaml
* removed user agent from specs
the user agent check for lollipop was removed in https://github.com/pagopa/io-backend/commit/be58f30a1a44283dc6ee5d392629855c420078b3 , but it was mistakenly left in the OpenAPI specs.
> removed user agent from specs

- openapi/consumed/api-piattaforma-notifiche.yaml
- openapi/consumed/api-third-party.yaml
- src/__mocks__/pn.ts
- src/adapters/__tests__/pnFetch.test.ts
- src/adapters/pnFetch.ts
- src/controllers/messagesController.ts
- src/services/__tests__/newMessagesService.test.ts
- src/services/newMessagesService.ts
* [Update pn api with the new endpoint](https://github.com/pagopa/io-backend/commit/806a1ac6c0ce3e3610f47f7fd88f43504ed4624a);
* [Update PN fetch in order to handle the new endpoint](https://github.com/pagopa/io-backend/commit/d4fc8523b4439d9d3c71b90260860544e8b573c9);
* [Update third party openapi](https://github.com/pagopa/io-backend/pull/1010/commits/a2c0d033555d35fa1bf3050cc052b53adb4a2fe8);
* [Implement getThirdPartyMessagePreconditionFromThirdPartyService](https://github.com/pagopa/io-backend/pull/1010/commits/40378d7c9aa01817688c4bffa0e9f4a25f670577);
This still is a work in progress, we need to add some test cases
> [IOCOM-189] Remove precondition mock

- openapi/consumed/api-piattaforma-notifiche.yaml
> [#IOCOM-227] Fix pn precondition path

- .env.example
- README.md
- helm/values-prod01.yaml
- src/config.ts
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/authenticationController.ts
- src/types/commons.ts
- src/utils/__tests__/ioLoginUriScheme.test.ts
- src/utils/ioLoginUriScheme.ts
This PR depends on https://github.com/pagopa/io-infra/pull/560
* new REQUIRED env variable `BACKEND_HOST` that stores the absolute URL of the app service
* new Feature Flag that decides the URIScheme provided to the redirect endpoint(in response to a POST made to the `/acs` endpoint)
transition to a custom URIScheme for APP development(transition managed by a feature flag)
> [#IOPID-204] IOLOGIN FF implementation

- src/services/__tests__/redisSessionStorage.test.ts
- src/services/redisSessionStorage.ts
Add `SESSION-` prefix for checking active session
Bugfix anonymous push notifications
Unit test, io-mock
> [#IOPID-303] Add `SESSION-` prefix for checking active session

- src/adapters/pnFetch.ts
- src/clients/third-party-service-client.ts
- src/utils/lollipop.ts
> [#IOCOM-314] Add some lollipop logs

- src/adapters/pnFetch.ts
- src/clients/third-party-service-client.ts
- src/services/newMessagesService.ts
- src/utils/lollipop.ts
- [fix lollipop locals in third party client](https://github.com/pagopa/io-backend/pull/1025/commits/fe37645ac547164eb16ec3f3a27dfd081964ea66)
> [#IOCOM-315] fix lollipop locals in third party client

- src/app.ts
- src/config.ts
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/authenticationController.ts
> [#IOPID-344] fix: set lollipop keys to long-lasting ttl when LV is enabled

- src/services/__tests__/redisSessionStorage.test.ts
- src/services/redisSessionStorage.ts
- add TTL to `saveSessionInfo` method
- remove legacy code on `listUserSessions`
- update tests and remove legacy ones
LV
- [c] Bug fix (non-breaking change which fixes an issue)
> [#IOPID-352] set TTL when saving session info

- src/controllers/__tests__/messagesController.test.ts
- src/controllers/messagesController.ts
* [Use legacy lollipop extract on tp](https://github.com/pagopa/io-backend/commit/ccf6eca0151b621d02ed236abe0334ad17aad4c9);
> [#IOCOM-357] Use legacy lollipop extract on tp

- .env.example
- src/__mocks__/lollipop.ts
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/__tests__/notificationController.test.ts
- src/controllers/__tests__/sessionLockController.test.ts
- src/controllers/authenticationController.ts
- src/controllers/notificationController.ts
- src/controllers/sessionLockController.ts
- src/services/ISessionStorage.ts
- src/services/__tests__/redisSessionStorage.test.ts
- src/services/redisSessionStorage.ts
- src/types/__tests__/asertionRef.test.ts
- src/types/assertionRef.ts
In order to verify the new LV user session, we need to check the presence of redis key KEYS-{CF}.
To do so, we needed to update the key format, storing the login type (LV / LEGACY)
This is the first step, that introduces the new decoder
> [#IOPID-351] Refactor session verification for LV with Feature Flag

- src/utils/spid.ts
> [#IOPID-421] fiscalNumber to uppercase during fast-login

- .env.example
- src/app.ts
- src/config.ts
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/authenticationController.ts
- src/utils/__tests__/cie.test.ts
- src/utils/cie.ts
This PR depends on https://github.com/pagopa/io-infra/pull/621
* added whitelist for users that belongs to a CIE TEST environment
* added unit tests
being able to whitelist certain fiscal codes for CIE test environments
build, lint and unit tests passed
> [#IOCIT-278] added CIE TEST users whitelist

- api_cgn_operator_search.yaml
- openapi/api_cgn_operator_search.template.yaml
- openapi/generated/api_cgn_operator_search.yaml
- src/controllers/__tests__/cgnOperatorSearchController.test.ts
- src/services/cgnOperatorSearchService.ts
> [#PE-439, #PE-444] Pointed new specs for operator search api and fixed tests and code

- src/app.ts
Move from legacy middleware to new one for firstLollipopSign
Move from legacy middleware to new one
> [#IOPID-433] Update lollipop middleware for firstLollipopSign endpoint

- openapi/consumed/api-piattaforma-notifiche.yaml
- src/__mocks__/pn-response.ts
- src/__mocks__/pn.ts
- src/adapters/__tests__/pnFetch.test.ts
[added new pn fields for cancelled notifications](https://github.com/pagopa/io-backend/commit/c78607ebe6c0a5f64a9379e28b401f7c7dc34f09)
This pr adds two new fields to manage PN cancelled notifications
Unit test
> [#IOCOM-530] added new pn fields for cancelled notifications

- api_backend.yaml
- openapi/api_backend.template.yaml
- openapi/generated/api_backend.yaml
* Add the ref for the ProblemJson in case of a `504` in payment endpoints;
* Remove the 504 status code GET /payment-activations;
> Add ref to the 504 status code, also removed the 504 unused

- src/__mocks__/lollipop.ts
- src/types/__tests__/user.test.ts
- src/types/user.ts
- src/utils/__mocks__/spid.ts
- src/utils/spid.ts
- fix `getAuthnContextFromResponse` to handle saml2 namespace too. 
Spid level is not decoded properly from SAML Response.
Unit test
> [#IOPID-876] fix: Decode Spid Level from SAML Response

- api_backend.yaml
- openapi/api_fast_login.template.yaml
- [updated io functions commons version in api specs](https://github.com/pagopa/io-backend/commit/899d35dca531aa36e65f642c694bedaf71eea68b)
> [#IOCOM-566] updated io functions commons version in api specs

- api_backend.yaml
- openapi/api_backend.template.yaml
- openapi/generated/api_backend.yaml
Fixed pointer to specs to v1.6.0 in every place.
Client was generated with api-for-io.yaml, but models were generated from api-pagopa-proxy.yaml this was causing a bug in the beta app.
build and unit tests
> [#IOCOM-575] Fixed pointer to pagopa-proxy specs

- api_backend.yaml
- openapi/api_fast_login.template.yaml
- openapi/generated/api_backend.yaml
- openapi/generated/api_notifications.yaml
- package.json
- yarn.lock
- [updated io-functions-commons version](https://github.com/pagopa/io-backend/commit/50fa678c628ea04922d91ccdcba5aad52cf0f38c)
> [#IOCOM-370] updated io-functions-commons version

- api_session.yaml
- openapi/api_session.template.yaml
- openapi/generated/api_session.yaml
- src/controllers/__tests__/sessionLockController.test.ts
- src/controllers/sessionLockController.ts
Fix `authLock` endpoint body.
Bugfix
Unit test
> [#IOPID-858]  fix `api_session.yaml` openapi

- api_backend.yaml
- api_parameters.yaml
- openapi/api_fast_login.template.yaml
- openapi/api_parameters.template.yaml
- package.json
- src/controllers/servicesController.ts
- src/services/__tests__/functionAppService.test.ts
- src/services/functionAppService.ts
- yarn.lock
- [modified serviceId in path params with new PathTraversalSafePathParam…](https://github.com/pagopa/io-backend/commit/5c4a54594fa3091965e0c4ceb46247a2a5d0d8d4)
The type used for the service_id in the path param was not safe and a path traversal attack was possible. It is now been modified with the new PathTraversalSafePathParam to avoid this type of attacks
> [#IOCOM-151] ServiceId modified with PathTraversalSafePathParam type

- api_io_sign.yaml
- src/__mocks__/response.ts
- src/services/__tests__/ioSignService.test.ts
- src/services/ioSignService.ts
1. Add `x-io-sign-environment` header on `getSignatureRequest` endpoint
this header enable us to discriminate the environment on client side to include additional context on mixpanel events
> chore(io-sign): [SFEQS-1889] Add x-io-sign-environment header

- api_public.yaml
- openapi/api_public.template.yaml
- openapi/generated/api_public.yaml
Update public API openapi specs
The `test-login` support now lollipop parameters, the openapi must be aligned to be used in load test and other client integrations.
openapi validator
> [#IOPID-1108] Update Openapi for test login with lollipop

- README.md
- src/config.ts
Add a new ENV to enable the clock skew log event for SPID/CIE logins.
We need to monitor and debug errors in production for `errorCode: 21` in login process.
not tested
> [#IOPID-1145] Add configuration for Clock Skew logs events

- package.json
- src/app.ts
- src/config.ts
- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/authenticationController.ts
- src/controllers/fastLoginController.ts
- src/utils/__tests__/fastLogin.test.ts
- src/utils/__tests__/spid.test.ts
- src/utils/fastLogin.ts
- src/utils/spid.ts
- yarn.lock
This PR depends on https://github.com/pagopa/io-spid-commons/pull/153
- Refactor login type choice (based on FF)
- Add login type info into audit log data
Add login type opt-in to audit log data
Unit tests, io-mock
> [#IOPID-1148] Add login type opt-in to audit log data

- src/services/__tests__/bonusService.test.ts
- src/services/bonusService.ts
* [Return an empty array in getAllBonusActivations](https://github.com/pagopa/io-backend/commit/558eaed7c60882d1947e8a15b4318e20479bb4cb);
* [Remove unit test for getAllBonusActivations](https://github.com/pagopa/io-backend/commit/ffa154bf9b904def07d23ffcf40c0096bf65405e);
Dismiss holiday bonus
> [#IOCOM-207] Remove get all bonus activation implementation

- src/types/__tests__/profile.test.ts
- src/types/profile.ts
* [[#IOPID-1047] added property to toInitializedProfile utility method](https://github.com/pagopa/io-backend/commit/e691d4725ab9c7f61d9ac2a052634f9eb9ac6e37)
property was not returned afterall due to the conversion to `InitializedProfile` utility method
unit tests
> [#IOPID-1047] added property to toInitializedProfile utility method

- .github/workflows/pr_opex_api_public.yml
Empty pipeline to enroll it as action
GitHub can't add pipelines from non-master branches
> [EC-57] Add 'PR - Opex Dashboard api_public' action to GitHub

- src/controllers/__tests__/authenticationController.test.ts
- src/controllers/authenticationController.ts
- yarn.lock
This PR depends on https://github.com/pagopa/io-functions-app/pull/288 for sdk package publication
* [[#IOPID-1236] added optional is_email_validated field to notifyLogin call](https://github.com/pagopa/io-backend/commit/0b1643f72f6c51fa4f97d64549a8977e7acce349)
added new optional field on notifyLogin body
unit tests
> [#IOPID-1236] added optional is_email_validated field to notifyLogin during acs

- api_cgn_operator_search.yaml
- openapi/api_cgn_operator_search.template.yaml
- openapi/generated/api_cgn_operator_search.yaml
Added 401 to operator search specs.
Whenever the login expires, these apis should return 401.
unit tests
build
> [#PE-516] Added 401 to operator search apis whenever login is expired

- src/services/ioSignService.ts
changed type guard in `getEnvironmentFromHeaders` function
the current refinement does not work (it always return `false`)
io-mock + unit test
> fix(io-sign): [SFEQS-2089] Refine "is Headers" type guard

- api_io_sign.yaml
1. removed `ProblemJson` as response schema for 401 responses in `api_io_sign.yaml` 
The authentication middleware does not returns a serialized `ProblemJson` object, but a string. This cause decode errors on Firma con IO screens.
> fix(io-sign): [SFEQS-2098] response schema for HTTP 401

- .devops/code-review-pipelines.yml
- api_backend.yaml
* introduced validation of OpenAPI specs located in root directory during CI
this job was missing on the pipeline. the newly added job together with root OpenAPI specs will be removed
in a dedicated PR. the refactoring started with #955
**NOTE:** to fix the currently invalid `api_backend.yaml` a type is being edited in https://github.com/pagopa/io-backend/pull/1099/commits/b4b9bdbd7090e6544848bfc429d16dc6e5f98c6f. the file is mentioned in `io-app` repository and the generated type will change from old `PathTraversalSafePathParam` to `t.string`. however, since the `t.string` type is less restrictive, the app build doesn't fail(cc. @shadowsheep1). backend side, the decoder is present in front of `upsertServicePreference` api call but it's missing in `getService` api call. a PR with a fix …
> [#IOPID-1469] introduce validation job on root api specs

- src/services/__tests__/profileService.test.ts
- src/services/profileService.ts
- yarn.lock
* [[#IOPID-1446] updated fn-app sdk](https://github.com/pagopa/io-backend/commit/3556c9b5b1538727300ff90726203ff16cbe11aa)
* [[#IOPID-1446] name inside updateProfile and emailValidationProcess calls](https://github.com/pagopa/io-backend/commit/cd7c4b61357cd214c8e6e5fb07de87cf730978a6)
pass name inside those endpoints to let validation mail have the profile name
unit tests, integration tests via io-mock
> [#IOPID-1446] profile name inside updateProfile and validationProcess

- package.json
- yarn.lock
* [[#IOPID-1737] updated spid-commons library](https://github.com/pagopa/io-backend/commit/833de7f64e24aa2c31728bf02e66d779e0dbb870)
update dependency to return new error for a specific scenario
integration tests via `io-mock`
> [#IOPID-1737] update spid-commons library

- api_services_app_backend.yaml
- openapi/api_services_app_backend.template.yaml
- openapi/generated/api_services_app_backend.yaml
Services App Backend OpenApi Update.
- Add optional `organization_name` property to **FeaturedService**
> [IOPAE-1124] Add organization_name to featured service

- api_services_app_backend.yaml
- openapi/api_services_app_backend.template.yaml
- openapi/generated/api_services_app_backend.yaml
Fix FeaturedService openapi schema.
- update `FeaturedService` schema
There was an indentation error.
With this fix, the `generate` command now generates correct **_FeaturedService_** model.
> fix[#IOPAE-1124]: Fix FeaturedService openapi schema

- api_services_app_backend.yaml
- openapi/api_services_app_backend.template.yaml
- openapi/generated/api_services_app_backend.yaml
New openapi specifications for _**featured institutions**_ and _**featured services**_.
- add new `GET /institutions/featured` openapi spec _(for featured institutions)_
- add new `GET /services/featured` openapi spec _(for featured services)_
This is a rework required for an updated version of featured intitutions and services management for **_Services Redesign_** stream.
> [IOPAE-1140] Add new featured institutions and services api specs

- .github/workflows/opex_api_services_app_backend.yml
- .github/workflows/pr_opex_api_services_app_backend.yml
- .opex/api_services_app_backend/env/prod/backend.ini
- .opex/api_services_app_backend/env/prod/backend.tfvars
- .opex/api_services_app_backend/env/prod/config.yaml
- .opex/api_services_app_backend/env/prod/terraform.tfvars
Add opex dashboard for api services app backend
> [#IOPAE-1167] Add opex dashboard for api services app backend

- package.json
- yarn.lock
* Restore applicationinsight older version
* Use resolution to avoid build error with `io-functions-commons`
We need to resolve the conflict between io-backend and io-functions-commons
> [IOCOM-1432] fix: use resolution for applicationinsights dependency

- src/app.ts
> hotfix: mount getTrialSubscription on express app

- package.json
- src/clients/io-wallet.ts
- src/controllers/ioWalletController.ts
- src/services/__tests__/ioWalletService.test.ts
- src/services/ioWalletService.ts
1. Added `generate:api:io-wallet` script in `package.json`
2. Added `IoWalletAPIClient`
3. Added `IoWalletService` with `getUserByFiscalCode` method
4. Added `retrieveUserId` function
5. Added unit tests for `IoWalletService`
> chore: [SIW-1111] Added IoWalletAPIClient and IoWalletService

- api_backend.yaml
- openapi/generated/api_backend.yaml
- package.json
- yarn.lock
* [chore(deps): update io-functions-commons to the latest version](https://github.com/pagopa/io-backend/commit/fefd5df51bcc80cdd962aca67630d9f2011a9bec);
* [feat(openapi): add organization fiscal code when the get of a single …](https://github.com/pagopa/io-backend/commit/357f695c898837d11bdf2177749a25400c6e424a);
io-app need this property.
unit test.
> [IOCOM-1462] Add organization fiscal code when a single message is returned with public_message=true

- helm/values-prod01.yaml
Patch services app be url
Service App BE Fn name has changed
- Service App BE Fn URL configuration
In order to configure the correct Service App BE Fn URL
> chore:[IOPAE-1196] Update values-prod01.yaml

- src/config.ts
> [SIW-1205] fix IoWalletAPIClient

- .opex/api_services_app_backend/env/prod/config.yaml
- .opex/api_services_app_backend/env/prod/terraform.tfvars
> [#IOPAE-1271] update io-services-app-be dashboard

- .devops/deploy-pipelines.yml
> deploy to new backendl3

- api_io_wallet.yaml
- package.json
- src/controllers/ioWalletController.ts
- src/services/__tests__/ioWalletService.test.ts
- src/services/ioWalletService.ts
1. Fixed the content-type returned by `createWalletAttestation`
2. Added the new OpenAPI in the `generate:api:io-wallet` script and handled new error codes returned
> fix: [SIW-1345] fixed createWalletAttestation returned object

- api_trial_system.yaml
- openapi/api_trial_system.template.yaml
- openapi/generated/api_trial_system.yaml
- Update basePath on api_trial_system
The basePath of the open-api is wrong. The generated clients does not use the basePath, so this change is marked as Chore
N/A
> Update basePath of api_trial_system

- api_io_wallet.yaml
- package.json
- src/controllers/ioWalletController.ts
- src/services/__tests__/ioWalletService.test.ts
- src/services/ioWalletService.ts
> [SIW-1387] updated createWalletAttestation content-type

- api_io_wallet.yaml
- package.json
- src/services/ioWalletService.ts
Added `409` status code for `/wallet-instances` and `/token` wallet endpoints
> [SIW-1446] return integrity check error

- .opex/api_backend/env/prod/config.yaml
- .opex/api_notifications/env/prod/backend.ini
- .opex/api_notifications/env/prod/backend.tfvars
- .opex/api_notifications/env/prod/config.yaml
- .opex/api_notifications/env/prod/terraform.tfvars
* Send `api_backend` alerts also to `io_com_monitor` slack channel;
* Move `api_notifications` alerts to `io_com_monitor` slack channel.
We want to isolate `io_com` related alerts into this new slack channel.
> [IOCOM-1702] chore: add new action group for io_com_monitor

- .devops/deploy-pipelines.yml
DEPENDS ON https://github.com/pagopa/io-infra/pull/1199
Add appbackend l3 in deployment workflow
For the publishing of the IT Wallet, many resources will be impacted with higher traffic. For this reason, most of them must be scaled up.
More information [here](https://pagopa.atlassian.net/wiki/spaces/EC/pages/1261764890/Risorse+Impattate).
> [CES-128] - Add appbackend l3 in deployment workflow

- package.json
- src/controllers/ioWalletController.ts
- src/services/__tests__/ioWalletService.test.ts
- src/services/ioWalletService.ts
> chore: [SIW-1706] Removed PDV user id

- api_backend.yaml
- openapi/api_backend.template.yaml
- openapi/generated/api_backend.yaml
> [#IOPID-2429] Remove dangling OpenApi definitions

- api_io_wallet.yaml
- package.json
- src/app.ts
- src/controllers/ioWalletController.ts
- src/services/__tests__/ioWalletService.test.ts
- src/services/ioWalletService.ts
Added new wallet endpoint `GET /wallet-instances/current/status`
It is needed to get the current wallet instance status
> feat: [SIW-1775] Added wallet endpoint

- api_trial_system.yaml
- openapi/api_trial_system.template.yaml
- openapi/generated/api_trial_system.yaml
- Update description of `404` response on `getSubscription` operation
- Update description of `201` and `202` responses on `createSubscription` operation
- Improve description of `SubscriptionState` schema
We want to clarify the usage of the Trial System API
> [IOPLT-773] Update descriptions of Trial System API operations and schemas

- api_io_wallet.yaml
- package.json
- src/app.ts
- src/controllers/ioWalletController.ts
- src/services/__tests__/ioWalletService.test.ts
- src/services/ioWalletService.ts
1. Replaced `GET /wallet-instances/current/status` endpoint with `GET /wallet-instances/{id}/status` to get a specific wallet instance status
2. Added `PUT /wallet-instances/{id}/status` to revoke a specific wallet instance status
> feat: [SIW-1775] Add getWalletInstanceStatus and setWalletInstanceStatus endpoint

- .devops/deploy-pipelines.yml
Removed backend l3 from deploy pipeline
backend l3 does not exist anymore
> [#PE-597] Removed backendl3 from deploy

- src/routes/publicRoutes.ts
Add the right base path to the `status`route
bugfix
> [#IOPLT-958] Fix base path status API

- .github/workflows/code_review.yaml
- .github/workflows/deploy-pipelines.yml
- .identity/00_locals.tf
- .identity/00_main.tf
- README.md
- api_io_wallet.yaml
- api_services_app_backend.yaml
- openapi/api_services_app_backend.template.yaml
- openapi/consumed/api-piattaforma-notifiche.yaml
- openapi/generated/api_services_app_backend.yaml
- package.json
- scripts/build-tools.sh
- scripts/build.sh
- scripts/generate-proxy-api-models.sh
- scripts/test.sh
- scripts/yarn.sh
> [#IOPLT-950] Add new GA pipeline for code review

- .github/workflows/code_review.yaml
- .github/workflows/deploy-pipelines.yml
> [IOPLT-950] Update deploy pipeline

- .changeset/ready-groups-wear.md
> [SIW-2079] run changeset

- .changeset/lazy-olives-argue.md
- api_io_wallet.yaml
- package.json
- src/controllers/ioWalletController.ts
- src/routes/ioWalletRoutes.ts
- src/services/__tests__/ioWalletService.test.ts
- src/services/ioWalletService.ts
Added `wallet-attestation` wallet endpoint
> [SIW-2091] feat: added /wallet-attestation wallet endpoint

- .github/workflows/call_opex_api.yml
- .github/workflows/call_pr_opex_api.yml
- .opex/api_backend/env/prod/config.yaml
- .opex/api_io_fims/env/prod/config.yaml
- .opex/api_public/env/prod/config.yaml
- .opex/api_services_app_backend/env/prod/config.yaml
- .opex/api_trial_system/env/prod/config.yaml
Update `opex-dashboard-azure-action` image to fix Opex alert data-source upgrade
> [#IOPLT-1264] fix alert datasource update error

- .opex/api_services_app_backend/env/prod/config.yaml
> [IOPAE-2158] change services app backend opex action group
