api.yaml, public/profile.html, src/controllers/__tests__/profileController.test.ts, src/services/__tests__/profileService.test.ts, src/types/__tests__/profile.test.ts, src/types/api_client/extendedProfile.ts
Adds isWebhookEnabled to all required types
Points the swagger definitions to a tag instead of a commit
=> [#155934507] Pass the isWebhookEnabled preference from app to API backend (and vice versa)

package.json
As mentioned [here](https://github.com/Azure/autorest.typescript/issues/80) by default Autorest uses the latest version for the extensions used to perform the client generation. It could happens that the extension's version is out of sync and this could cause generation failures.
This PR is aimed to fix the extension version of the typescript generator
=> Fix autorest typescript extension to a know version

package.json
This version introduce the `create_at` field for messages and it is needed by the APP to correctly generate type definitions
=> Bump to version 0.0.19

package.json, src/controllers/__tests__/authenticationController.test.ts, src/strategies/spidStrategy.ts, src/types/__tests__/user.test.ts, src/types/user.ts
This is to simply log the assertion to the container logs to see what is wrong actually, then we have to store the logs in a more persistent storage
=> [#158818736] Log the xml assertion

src/controllers/__tests__/authenticationController.test.ts, src/controllers/authenticationController.ts, src/controllers/notificationController.ts, src/services/notificationService.ts, src/types/commons.ts, src/types/notification.ts
Actually the Backend redirect the user to the IDP Logout page causing the APP to fail when making the request to `/logout`. We already discussed that we don't need to perform the real IDP Logout because the IDP Session timeout after 15 minutes. This PR make the Backend return 200 with an empty body object.
=> [#158998658] Return 200 on /logout

src/container.ts
I'm not familiar with Awilix, but it seems that without the `singleton()` modifier, a new client will be created each time a component needs it...
=> Create only one Redis client per node

src/services/pagoPAClientFactory.ts, src/services/pagoPAProxyService.ts
When PagoPaProxy provides a specific error 500, Backend uses a whitelist to check if the error should be forwarded to applicant
=> [#159519359] Remove conn retry on error 500 + Add a whitelist for errors to forward

api_proxy.yaml, src/controllers/pagoPAController.ts, src/controllers/profileController.ts, src/services/__tests__/profileService.test.ts, src/services/profileService.ts, src/types/__tests__/profile.test.ts, src/types/profile.ts
The previous `ProfileWithoutEmail` / `ProfileWithEmail` types created confusion on which attributes were actually coming from the APIs - in this PR I'm changing the names of the types and removing the API fields from the temporary SPID profile.
=> Return profile fields that are either from a temporary SPID profile or from an initialized API profile

src/app.ts, src/controllers/authenticationController.ts, src/utils/getErrorCodeFromResponse.ts
This PR aims to attach error numbers found in the SAML XML assertion, received by SP's "assertionConsumerService", to the error page URL "`/error.html`" coming from the IdP sever.
That way the resulting URL sent to the app client should be "`/error.html?errorCode=XX`".
=> [#161981230] bind error code to page url

.env.example, Dockerfile, docker-compose.yml, package.json, src/__tests__/server.test.ts, src/server.ts, src/utils/gracefulShutdown.ts, yarn.lock
[#166152893] - Il backend deve terminare in modo controllato alla ricezione di un SIGTERM o SIGINT
=> [#166152893] Gracefully shutdown on SIGTERM and SIGINT 

src/services/__tests__/redisSessionStorage.test.ts, src/services/redisSessionStorage.ts
When a new session is created for a user all the older will be removed. `SessionInfo` for all the previous sessions remain. The method `clearExpiredSetValues` now is never called, so expired sessions remain into the session history.
=> [#165307029] On new login, invalidate existing sessions

.env.example, Dockerfile, README.md, docker-compose.yml
npmrc instructions are missing
docker-compose doesn't mount .env file using :delegated
Dockerfile does not have step for copying npmrc file into docker image
/etc/hosts mapping should be based on ip instead of 'localhost'
=> [#171154124] fix local development

api_backend.yaml, api_notifications.yaml, api_pagopa.yaml, src/config.ts, src/controllers/__tests__/notificationController.test.ts, src/controllers/notificationController.ts, src/services/__tests__/notificationService.test.ts, src/services/notificationService.ts
Makes the notification endpoint accepting notification without content (in other words, notification objects that carries a `CreatedMessageWithoutContent`). These let's handling messages from services that don't want the content to be shown into the push notification preview.
=> [#171916455] accept notifications without content

src/services/__tests__/notificationService.test.ts, src/services/notificationService.ts
When sending push notification target only the last device that set the installationId (in other words, the last device where the user logged in successfully). This limits sending push notification to just one device owned by the user.
=> [#168929351] fix installationId to last device

src/__mocks__/request.ts, src/app.ts, src/clients/bonus.ts, src/controllers/__tests__/bonusController.test.ts, src/controllers/bonusController.ts, src/services/__tests__/bonusService.test.ts, src/services/bonusService.ts
* implemented proxy endpoint for bonus' `getLatestBonusActivationById`
* fixed some wrong tests for `getBonusEligibilityCheck`
* updated to last version of bonus API spec
* updated mocks
`getLatestBonusActivationById` should return a `BonusActivationWithQrCode`, but so far it returns just a `BonusActivation` as the qrcode generation part isn't implemented yet
=> [#173017529] Add bonus activation detail endpoint

api_bonus.yaml
This PR adds the missing section **securityDefinitions**
```yaml
securityDefinitions:
Bearer:
type: apiKey
name: Authorization
in: header
```
=> [#173241768] Add securityDefinitions in bonus API spec

api_session.yaml
This is a workaround needed in order to have these endpoints protected by token. The token is defined as a simple parameter instead of inside a proper security definition. 
* We must pass the auth key as `token` querystring. This is because the [passport plugin we use](https://github.com/mbell8903/passport-auth-token) fails to handle header params
* We must define it as a parameter. This is because our `io-utils` code generators fails to handle security definitions which are not header parameters.
=> [#173944273] Fix authentication specification on Session API

package.json, src/app.ts, src/server.ts, yarn.lock
New `io-spid-commons` for events tracking.
This Draft PR require a new release of `io-spid-commons` from pagopa/io-spid-commons#49
=> [#174710289] Add SPID/CIE events tracking

api_backend.yaml, src/app.ts
This PR includes a minor refactoring of `GetSupportToken` endpoint. It will be changed from `/token` to `/token/support`.
=> [#175679733] Rename GetSupport Token endpoint

src/utils/strategies.ts
Atm the passport middleware returns 401 in case of system errors; it must return 500 otherwise the user is logged out.
Draft since it needs unit and integration tests.
=> [#176003320] Return 500 instead of 401 on system errors

package.json, src/__tests__/app.test.ts, src/utils/middleware/checkIP.ts, yarn.lock
Actually, the source IP we got from x-client-ip is the one of the application gateway (10.x.x.x). 
This PR takes it from the original client instead.
=> [#176077315] Get client ip from x-forwarded-for header

.env.example, README.md, src/app.ts, src/config.ts, src/utils/middleware/__tests__/dueDate.test.ts, src/utils/middleware/dueDate.ts
As users cannot request Bonus Vacanza after a given date, we introduce a middleware prior to `startBonusEligibilityCheck` and `startBonusActivationProcedure` operations that makes them unavailable after such date.
Reading operations are kept available.
| Variable name                          | Description                                                                       | type   |
|----------------------------------------|-----------------------------------------------------------------------------------|--------|
| BONUS_REQUEST_LIMIT_DATE               | The date until a user can request a bonus, in UTC ISO format                      | string |
=> [#176257846] Disable bonus requests at a given date

src/utils/middleware/checkIP.ts
This is a fix since req.connection.remoteAddress returns the internal docker host IP
=> [#176314485] Use x-client-ip for internal calls

api_pagopa.yaml, api_public.yaml, src/controllers/authenticationController.ts
We found that the following api specification weren't valid OpenAPI documents:
* api_pagopa
* api_public
As we generate definitions from such files, build has to be fixed in order for types to match.
=> [#176559282] [#176559344] Fix wrong definition on pagopa api and public api specifications

api_bonus.yaml
There is no need to define the `items` attribute of an array field to be required, but this makes the specification not valid
=> [#176561900] Fix bons api OpenAPI specification

api_cgn.yaml, package.json, src/controllers/__tests__/cgnController.test.ts, src/controllers/cgnController.ts, src/services/__tests__/cgnService.test.ts, src/services/bonusService.ts, src/services/cgnService.ts, src/utils/errorsFormatter.ts, src/utils/responses.ts
- Add `getCgnActivation` API implementation
- Add API specs
- Add tests
Provide an IO Backend proxying and implementation of the `getCgnActivation` [API](https://github.com/pagopa/io-functions-cgn/pull/14). It is used to provide a polling endpoint and let know to IO App, the status of an activation process. See the related Pivotal [story](https://www.pivotaltracker.com/story/show/176782092) for further informations.
It has been tested by performing unit tests.
=> [#176782092] Add Get Cgn Activation API

api_cgn.yaml, package.json, src/app.ts, src/controllers/__tests__/cgnController.test.ts, src/controllers/cgnController.ts, src/services/__tests__/cgnService.test.ts, src/services/cgnService.ts
- Add `getEycaStatus` API
- Add tests
While a citizen requests for a CGN and he's between 18 up to 30 years old, he wants also activate an EYCA card ( CGN and EYCA are co-badged ). We need to provide an API that could return detailed information about an EYCA Card.
It has been tested by performing unit tests .
=> [#177017837] added getEycaStatus api

api_cgn.yaml, package.json, src/app.ts, src/controllers/__tests__/cgnController.test.ts, src/controllers/cgnController.ts, src/services/__tests__/cgnService.test.ts, src/services/cgnService.ts
- Add `startEycaActivation` Api specs
- Add `getEycaActivation` Api specs
- Add tests
While a citizen requests for a CGN and he's between 18 up to 30 years old, he wants also activate an EYCA card ( CGN and EYCA are co-badged ), but in case of something goes wrong in EYCA activation, it must be possible to call directly EYCA activation from APP ( user retries ), see this [PR](https://github.com/pagopa/io-functions-cgn/pull/20) for function's side implementation.
It has been tested by performing unit tests and integration test.
=> [#176924316] Add EYCA activation API

api_cgn.yaml
This PR adds missing remote references:
- $ref: "#/definitions/EycaCardActivated"
- $ref: "#/definitions/EycaCardRevoked"
- $ref: "#/definitions/EycaCardExpired"
=> [#177060696] Add missing remote references

api_cgn.yaml, src/controllers/cgnController.ts, src/services/__tests__/cgnService.test.ts, src/services/cgnService.ts
This PR adds proper error responses on `getEycaStatus` used to manage particular case of errors. See [this](https://github.com/pagopa/io-functions-cgn/pull/29) for further informations.
=> [#177081289] Add Conflict and Forbidden responses on getEycaStatus

api_cgn.yaml, package.json, src/app.ts, src/controllers/__tests__/cgnController.test.ts, src/controllers/cgnController.ts, src/services/__tests__/cgnService.test.ts, src/services/cgnService.ts
- Add `generateOtp` API Specs
- Add tests
Since a CGN could be used to obtain discounts over online's purchase, we must provide an API that could generate an OTP, to be used in the checkout phase through third-parties e-commerce portal. See this [story](https://www.pivotaltracker.com/story/show/175761529) for further informations.
Unit tests
=> [#175761529] Add CGN generate OTP API

.env.example, api_cgn.yaml, src/app.ts, src/config.ts, src/controllers/__tests__/cgnController.test.ts, src/controllers/cgnController.ts, src/types/commons.ts
- Add Allowed CGN Fiscal Codes env variable
- Add CgnController internal middleware `withAllowedUser`
- Add tests
In order to provide an internal MVP of CGN functionalities, we must allow only a subset of fiscal codes that can perform api calls. See this [story](https://www.pivotaltracker.com/story/show/177137914) for further informations.
Unit tests
=> [#177137914] Add Allowed Test Fiscal Codes

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml
We need to use `azure-pipelines-template` with a version of 15 or higher, in order to use the fix adopted into https://github.com/pagopa/azure-pipeline-templates/pull/83 and make healtcheck steps to work again
=> Update pipelines templates to v15

package.json
Set `1.27.0` as minimum app version. This information is consumed by APP IO to force users to update in case they have a lower version
=> Bump app min version

api_notifications.yaml, src/services/__tests__/notificationService.test.ts
- moved to v21.0.0 file definitions in api_notifications.yaml
In order to upgrade fn-services to @pagopa/ts-commons we need to upgrade api_notifications.yaml to use it instead of  italia-ts-commons
=> [IP-324] update `api_notification.yaml` definitions to latest fn-commons

.env.example, src/config.ts, src/controllers/__tests__/authenticationController.test.ts, src/controllers/authenticationController.ts
The `ClientErrorRedirectionUrl` for minors of 14 yo returns only the query param `errorCode`. `errorMessage` was removed. The newer app versions will handle all the query params sent with the redirect url pagopa/io-app#3642
The actual version of the IO App cannot handle properly the error when `errorMessage` prop is defined with `errorCode`.
Unit test
=> [#IC-182] Remove errorMessage from CIE redirect error url params

package.json
This PR upgrades `min_app_version` to 1.38.0
[more info](https://pagopa.atlassian.net/wiki/spaces/IOAPP/pages/462258341/Versione+minima+app+OS#Update-24-Marzo-2022-1.38.0.12)
=> [IA-755] Upgrade `min_app_version` to 1.38.0

api_backend.yaml, package.json, src/controllers/messagesController.ts, src/services/__tests__/newMessagesService.test.ts, src/services/newMessagesService.ts
This PR depends on https://github.com/pagopa/io-functions-app-messages/pull/17
- Handle 403 response type in upsertMessageStatus from fn-app-messages
- Add 403 response to api_backend.yaml
=> [IC-395] add 403 response to upsert message status

api_backend.yaml, package.json, src/controllers/servicesController.ts, src/services/__tests__/functionAppService.test.ts, src/services/functionAppService.ts
Add new Service preference to handle read message status
Update the specification for `GetServicePreference` and `UpsertServicePreference` APIs.
The Service Preference model was extended to handle a new preference that allow the sender to get the read status for the sent message.
The user can disable this feature using the new preference `can_access_message_read_status: false`.
not yet
=> [#IOCIT-6, #IOCIT-5] Add can_access_message_read_status to ServicePreference

src/app.ts
Problem:
Calling the getThirdPartyAttachment endpoint with the path relative to a file on PN, it returns 404.
This is due to express routing: the path `${basePath}/third-party-messages/:id/attachments/:attachment_url` does not support `attachment_url` parameters containing `/`, so it tries to redirect the request to a non-existent endpoint.
Fix routing path to allow `/` in `attachment_url` parameter
Manually running io-mock
=> [#ICC-144] Fix getThirdPartyAttachment routing

api_pn.yaml, src/app.ts, src/controllers/__tests__/pnController.test.ts, src/controllers/pnController.ts, src/services/__tests__/pnService.test.ts, src/services/pnService.ts
New Endpoint to read the Activation status for Piattaforma Notifiche special service.
New PN service and controller
Refactor PnService structure for more compact initialization.
The _Piattaforma Notifiche Avvisi di cortesia_ special service need two endpoint to read the current activation status and update the value. This PR introduce the new endpoint for reading the current activation status on PN servers, returning this information to the IO App.
Unit Test
=> [#IOCIT-35] Get Activation for PN courtesy service

src/services/redisSessionStorage.ts, src/utils/__tests__/redis.test.ts, src/utils/redis.ts
Obfuscate tokens included in error messages sent to App Insights custom events.
Token can be sent to AI on custom events on errors. Before sending the message token info must be obfuscated or redacted.
unit test
=> [#IOCIT-285] Offuscate Tokens in Custom events payload

.devops/code-review-pipelines.yml, .gitignore, openapi/generated/lollipop_definitions.yaml, package.json, src/__tests__/lollipop.test.ts
- Added new `lollipop_definitions.yaml` in `openapi/generated`
- Added tests for verifying regex
Enable LolliPoP endpoint definition.
Lollipop will require following header:
- `x-pagopa-lollipop-original-method` (custom)
-  `x-pagopa-lollipop-original-url` (custom)
- `content-type`
- `content-length`
- `content-digest`
- `signature-input` (it contains `nonce`, `alg` and `keyid` (the fingerprint) )
Unit tests
=> [#ICC-296]  Add LolliPoP header definitions

.env.example, README.md, src/__mocks__/request.ts, src/app.ts, src/config.ts, src/handlers/__tests__/lollipop.test.ts, src/handlers/lollipop.ts
- Refactoring `lollipop` middleware on login flow
- Add Feature flag to enable/disable Lollipop flows globally
- Add Unit tests
- Add io-fn-lollipop env config variables
- Update README
- Update env.example
This is required in order to accomplish client's public key reservation in the login flow, enabling lollipop activation's first step
This PR depends on https://github.com/pagopa/io-infra/pull/447
Unit test
=> [#IOCIT-323] Add support for pubKey reservation

src/app.ts, src/config.ts, src/controllers/__tests__/authenticationController.test.ts, src/controllers/__tests__/notificationController.test.ts, src/controllers/__tests__/pagoPAController.test.ts, src/controllers/__tests__/profileController.test.ts, src/controllers/__tests__/sessionController.test.ts, src/services/ISessionStorage.ts, src/services/__tests__/redisSessionStorage.test.ts, src/services/redisSessionStorage.ts, src/strategies/__tests__/bearerZendeskTokenStrategy.test.ts
Created utility into the `RedisSessionStorage` for reading, writing and deleting reference from user fiscal codes and assertionRefs for the lollipop protocol.
To be able to retrieve the key related to a user is needed the introduction of a new key on redis with the fiscalCode as key and the key thumbprint as value. The value has the algorithm used to calculate the thumbprint as prefix.
unit test
=> [#IOCIT-320] RedisSessionStorage can manage CF-assertionRef link for lollipop

src/controllers/__tests__/authenticationController.test.ts, src/controllers/authenticationController.ts, src/services/ISessionStorage.ts, src/services/redisSessionStorage.ts
If lollipop is enabled:
- retrieve of assertionRef from redis
- delete of CF-assertionRef binding from redis
- sending of public key revoke message
When lollipop is enabled and user log out from the app all lollipop data must be deleted.
- yarn build
- yarn test
- yarn lint
TODO: lollipop data flow tests, now lollipop is disabled on tests.
=> [#IOCIT-296] Modified logout to delete lollipop data before destroying session.

Dockerfile, docker-compose.yml, src/controllers/__tests__/authenticationController.test.ts, src/controllers/authenticationController.ts, src/strategies/localStrategy.ts, src/types/__tests__/user.test.ts, src/types/user.ts
Add `getSamlResponseXML` method in SpidUser.
We need to extract the whole SAML Response to initialize Lollipop and/or complete a login with test-login endpoint.
unit test
=> Fix parse SamlResponse to get InResponseTo value

src/services/__tests__/newMessagesService.test.ts, src/services/newMessagesService.ts
- [fixed using iun instead of messageId for third party precondition api](https://github.com/pagopa/io-backend/pull/1014/commits/30acdf8df3aa11ae601b513ffeb6e38f7e14c2a6)
=> [#IOCOM-227] fixed using iun instead of messageId for third party precondition api

README.md, api_public.yaml, package.json, src/app.ts, src/config.ts, src/controllers/__tests__/authenticationController.test.ts, src/controllers/authenticationController.ts, src/utils/fastLogin.ts, yarn.lock
This PR depends on https://github.com/pagopa/io-spid-commons/pull/148
- Update io-spid-commons
- Enable new io-spid-commons functionality for handling additional data between login and acs steps.
- Add new FF management for LV functionality
- Create user's token based on LV FF
Enable new Fast Login management (based on FF).
Unit test, io-mock
=> [#IOPID-257] Handle new login type on `acs` callback

src/controllers/__tests__/sessionController.test.ts, src/services/ISessionStorage.ts, src/services/__tests__/redisSessionStorage.test.ts, src/services/redisSessionStorage.ts
- add new isUserSessionUpdate in RedisSessionStorage `set` function, for discriminating between creation and update
Bugfix for LV tokens
Unit tests
=> fix:[#IOPID-343] Discriminate if is a session creation or update

src/__mocks__/lollipop.ts, src/__mocks__/pn.ts, src/adapters/__tests__/pnFetch.test.ts, src/controllers/messagesController.ts, src/types/user.ts, src/utils/lollipop.ts, src/utils/middleware/__tests__/lollipop.test.ts, src/utils/middleware/lollipop.ts
New `withOptionalUserFromRequest` to retrieve the User if present
The Lollipop middleware verify the CF and AssertionRef from the request and the LCParams if the session is missing
add some validation on edge case
LV needs to use LolliPoP without an active user session. The Lollipop middleware now can be used even if the session token is not provided.
unit test
=> [#IOPID-376] The LolliPoP middleware can complete without an user session

src/app.ts, src/utils/lollipop.ts, src/utils/middleware/lollipop.ts
Restore the old lollipop middleware with legacy suffix used only for Firma con IO
Firma con IO send as keyid the assertionRef without the prefix, the new middleware fail the new validation step on the keyid format.
not tested
=> [#IOPID-382] Legacy LolliPoP middleware without assertionRef validation

src/controllers/__tests__/fastLoginController.test.ts, src/controllers/fastLoginController.ts, src/utils/spid.ts
* see commit history
for example, the previous implementation was failing if the email was not found, but the field in the type `UserWithoutTokens` was partial from the start. With this logic, if the field is partial, the user is correctly returned. 
unit tests
=> [#IOPID-387] user creation utility fails retrieving optional data

src/__mocks__/lollipop.ts, src/__tests__/lollipop-consumer.test.ts, src/app.ts, src/types/lollipop.ts, src/utils/__tests__/lollipop.test.ts, src/utils/lollipop.ts, src/utils/middleware/__tests__/lollipop.test.ts
Refactory of the LolliPoP middleware to handle LV flow without an active session.
The LV feature need to retrieve the assertionRef directly from the request. The keyId field into the `signature-inputs` header on other services (IO sign and PN) is evaluated with the thumbprint of the key (an assertionRef without the prefix). This refactory retrieve the assertionRef from the thumbprint.
unit test
=> [#IOPID-394] Refactory LolliPoP Middleware with thumbprint instead assertionRef as keyId

api_session.yaml, openapi/api_session.template.yaml, openapi/generated/api_session.yaml, src/app.ts, src/controllers/__tests__/sessionLockController.test.ts, src/controllers/sessionLockController.ts, src/services/ISessionStorage.ts, src/types/fiscalCode.ts
New `logout` endpoint
New `deleteUserSession` handler in `SessionLockController`
Refactor `lockUserSession` handler to remove duplicated code (`buildInvalidateUserSessionTask`)
Fix missing `delUserAllSessions ` in `ISessionStorage` interface.
New middleware `withFiscalCodeFromRequestParams ` to handle FiscalCode in params.
To invalidate the user session from IO-Web for the `FastLogin` feature is needed an internal endpoint of `io-backendli` for the Fast Login service. This operation need to invalidate the current session and all the lollipop related param of a specified user.
unit test
=> [#IOPID-756] Internal Logout endpoint for LV

api_backend.yaml, api_parameters.yaml, openapi/api_backend.template.yaml, openapi/api_parameters.template.yaml, openapi/generated/api_backend.yaml, openapi/generated/api_parameters.yaml, src/controllers/__tests__/messagesController.test.ts, src/controllers/messagesController.ts, src/services/__tests__/newMessagesService.test.ts, src/services/newMessagesService.ts
* [Restrict message id type to be an Ulid for messages endpoints](https://github.com/pagopa/io-backend/commit/cc04ef43535ca3e590289f3ee9d3039b10467f19);
We need a strict type check on every path param accepted as a string to address a potential security issue.
=> [#IOCOM-152] Restrict message id type to be an Ulid for messages endpoints

package.json, src/__mocks__/redis.ts, src/__tests__/app.test.ts, src/app.ts, src/controllers/__tests__/authenticationController.test.ts, src/controllers/__tests__/fastLoginController.test.ts, src/controllers/__tests__/notificationController.test.ts, src/controllers/__tests__/pagoPAController.test.ts, src/controllers/__tests__/profileController.test.ts, src/controllers/__tests__/sessionController.test.ts, src/server.ts, src/services/__tests__/redisSessionStorage.test.ts, src/services/redisSessionStorage.ts, src/strategies/__tests__/bearerZendeskTokenStrategy.test.ts, src/utils/redis.ts
New `RedisClientSelector` to select `SAFE` and `FAST` redis client.
Graceful shutdown for all the Redis clients.
Refactor `RedisSessionStorage` with the new selector, use SAFE mode for critical operations.
Refactor unit test (shared redis client mock).
The key that stores the `CF-AssertionRef` relationship on redis is used to validate the correct initialization of the lollipop protocol. When the validity of the stored value expires, the private key cannot be used to perform a lollipop operation. The read operation on Redis can return an expired key if the operation occurs on a slave instance. The `RedisClientSelector` creates 2 different Redis clients, the SAFE selector will return a client with `useReplicas=false` forcing the operation to be performed on the master node.
not yet
=> [#IOPID-346] Consistent Redis Client

src/app.ts, src/controllers/authenticationController.ts, src/handlers/__tests__/lollipop.test.ts, src/handlers/lollipop.ts, src/strategies/localStrategy.ts, src/utils/__mocks__/spid.ts
Test login support lollipop headers.
Test login reserve the provided key.
Test login generate a fake assertion with ResponseID and CF linked to the credential.
To executes load test for fast login capability is needed use lollipop with test login.
Test login can be used for lollipop functions in App for testing purposes.
local execution with `io-mock`
=> [#IOPID-1105] Add Lollipop capabilities on test login

src/adapters/pnFetch.ts
=> [#IOCOM-681] fixed query param decode in get third party attachments url

src/controllers/__tests__/messagesController.test.ts, src/controllers/messagesController.ts
Transferred query params from request to the attachment url.
Attachment url could have some query params so we must add them to the attachment url.
unit test
=> [#IOCOM-682] Included eventual query params in attachment url

src/app.ts, src/controllers/__tests__/sessionLockController.test.ts, src/controllers/sessionLockController.ts
- add deleteInstallation to lockUserAuthentiction flow](https://github.com/pagopa/io-backend/commit/fa4308d5be855b9917a2d8e98dbf0ea2f680c01b)
- add tests](https://github.com/pagopa/io-backend/commit/d6eacbdc6a825b6e7ee8926f977906650596a434)
Avoid to sent notifications to the user's device when a session lock occurred
Unit tests
=> [#IOPID-1201] Disable notifications when the user locks the session from ioapp.it

package.json, src/controllers/profileController.ts, src/services/profileService.ts, yarn.lock
`UpdateProfile` now returns `412` when the given e-mail is already used by another user. This PR align the backend response with the function-app.
Blocked by https://github.com/pagopa/io-functions-app/pull/290
this change is required to ensure the uniqueness of e-mail addresses
=> [IOPID-1052] Align backend to UpdateProfile (Return 412 error on email already taken)

src/__mocks__/setup.ts, src/services/__tests__/profileService.test.ts, src/services/profileService.ts, yarn.lock
Upgrade the `io-functions-app-sdk`
Handle a new 500 status code response from `GetProfile`
Upgrade unit test
The `fn-app` return a new 500 status code response from the `GetProfile` when an error occurs reading the unique email storage. We map this response with a custom response intead a unandled status code response.
unit test
=> [#IOPID-1264] Handle new InternalServerError response from GetProfile

.github/workflows/opex_api_fast_login.yml, .github/workflows/pr_opex_api_fast_login.yml, .opex/api_fast_login/env/prod/backend.ini, .opex/api_fast_login/env/prod/backend.tfvars, .opex/api_fast_login/env/prod/config.yaml, .opex/api_fast_login/env/prod/terraform.tfvars
- Add new GH action for managing OPEX dashboard and alert for `api_fast_login`
=> [#IOPID-1314] Add OPEX for `api_fast_login`

src/services/__tests__/ioSignService.test.ts, src/services/ioSignService.ts
Add a type guard to work with `req.headers` with the right runtime type (`Map` instead of `Record<string, string>`)
Due to a type annotation error on the generated api client, `getEnvironmentFromHeaders` wrongly assumed that `req.headers` was a `Record` instead of an `Headers` map, so the decode step has always failed.
=> fix(io-sign): [SFEQS-2089] Fix x-io-sign-environment header decode

src/config.ts, src/controllers/authenticationController.ts
- Add new env variable `IS_SPID_EMAIL_PERSISTENCE_ENABLED` (default `true`)
- when creating a new profile, store SPID email based on `IS_SPID_EMAIL_PERSISTENCE_ENABLED`
Avoid storing Spid email on first onboarding
Unit test
=> [#IOPID-1407] Avoid storing Spid email on first onboarding, based on `IS_SPID_EMAIL_PERSISTENCE_ENABLED`

src/app.ts, src/controllers/zendeskController.ts
- Trigger new `appbackend.zendesk.error` custom event
Raise an event when an error occurred on Zendesk token generation endpoint
=> [#IOPID-1453] Add event for Zendesk jwt errors

public/email_confirm.html
* [[#IOPID-1603] added new HTML static page](https://github.com/pagopa/io-backend/commit/b08e97a80518f916d8df17141455e7aef91e2561)
add new page for email validation confirm
local tests
=> [#IOPID-1603] added new HTML static page

api_services_app_backend.yaml, openapi/api_services_app_backend.template.yaml, openapi/generated/api_services_app_backend.yaml
This PR removes unused `/featured` api definition with its related schemas.
`/featured` API has been replaced by `/services/featured` and `/institutions/featured` APIs.
=> chore:[IOPAE-1143] OpenApi services app backend: remove unused /featured definition

.github/workflows/opex_api_trial_system.yml, .github/workflows/pr_opex_api_trial_system.yml, .opex/api_trial_system/env/prod/backend.ini, .opex/api_trial_system/env/prod/backend.tfvars, .opex/api_trial_system/env/prod/config.yaml, .opex/api_trial_system/env/prod/terraform.tfvars
- Add opex for trial-system
Set up alarms for the endpoints of the trial system provided by io-backend.
N/A
=> [IOPLT-641] Add opex alarms for trial-system

.env.example, package.json, src/clients/trial-system.client.ts, src/config.ts, src/services/trialService.ts
- Change environment name to `TRIAL_SYSTEM_APIM_KEY`
- Get `TRIAL_SYSTEM_APIM_BASE_PATH` variable
- Pass basePath variable when generating the client 
- Change OpenAPI URL used to generate client
> [!IMPORTANT]
> This PR depends on https://github.com/pagopa/trial-system/pull/197 which ensure the user group of the APIM subscription used by the backend can access to the endpoints.
> This depends on https://github.com/pagopa/io-infra/pull/1176 https://github.com/pagopa/io-infra/pull/1191 https://github.com/pagopa/io-infra/pull/1192 as well, which add the environment variables.
We are going to migrate the trial system calls through the APIM.
=> [IOPLT-699] Update API_KEY var name and OpenAPI url to generate trial system client

api_io_wallet.yaml, package.json, src/app.ts, src/controllers/ioWalletController.ts, src/services/__tests__/ioWalletService.test.ts, src/services/ioWalletService.ts
1. Added `PUT /wallet-instances/current/status` endpoint for user wallet instance revoke
2. Added unit tests
3. Added `503` as response status in wallet endpoint
=> feat: [SIW-1697] Added wallet instance revoke endpoint

src/app.ts, src/controllers/servicesController.ts, src/services/functionAppService.ts
GetVisibleServices API call was removed from App IO since 2.64.0 version and we recently incremented App IO minimum required version to 2.68.0, se we can remove it.
To take it easy, for the moment we replace the deprecated API handler with a stub response
[stub GetVisibleServices API](https://github.com/pagopa/io-backend/commit/3f84faaea97b80dc36729ab61787fbeb89c3d154)
To avoid downstream traffic
=> chore: [IOPAE-1390] stub GetVisibleServices API

package.json, yarn.lock
~~Update `jsonwebtoken` to version `9.0.2`~~
Remove `jsonwebtoken`
~~Security fix as described in https://github.com/auth0/node-jsonwebtoken/security/advisories/GHSA-8cf7-32gw-wr33~~
Unused since #1159
Unit tests.
=> [#IOPID-1713] Library `jsonwebtoken` removal

src/controllers/servicesController.ts, src/services/__tests__/functionAppService.test.ts, src/services/functionAppService.ts
Removed unnecessary `getVisibleService` API call, this proxied service is now stubbed cause is no longer called in new APP version
Unit tests
=> [#IOPAE-1478] removed getVisibleService Api call

.changeset/quick-radios-brush.md, api_io_wallet.yaml, package.json, src/controllers/ioWalletController.ts, src/routes/ioWalletRoutes.ts, src/services/__tests__/ioWalletService.test.ts, src/services/ioWalletService.ts
I've added:
- A new route in `ioWalletRoutes.ts`.
- A new method in `ioWalletController.ts` called `isFiscalCodeWhitelisted()`.
- A new method in `ioWalletService.ts` called `isFiscalCodeWhitelisted()`.
- The unit tests for the `isFiscalCodeWhitelisted()` in `ioWaleltService.test.ts`.
I've updated:
- The version of `io-wallet-user-func` azure function in `package.json` to generate new API and models.
The new endpoint is necessary for the simplified trial system development.
Adding and running unit tests for the new endpoint.
=> [SIW-2188] Added the isFiscalCodeWhitelisted() endpoint to check if the fiscal code is whitelisted
